'use client';

import { AlertTriangle, ArrowLeft, Check, ChevronDown, FileSpreadsheet, Save, Upload } from 'lucide-react';
import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from 'react';

type RecordValue = Record<string, unknown>;
type Field = { key:string; label:string; group:string; type:'text'|'textarea'|'number'|'boolean'|'json'; hint?:string; example?:string };

const FIELDS:Field[] = [
  {key:'name',label:'Nombre del agente',group:'Identidad',type:'text',example:'Agente Demo Innovate'},
  {key:'initialMessage',label:'Mensaje inicial',group:'Identidad',type:'textarea',example:'Hola, soy Andrés, agente especializado de Innovate. ¿En qué puedo orientarle?'},
  {key:'systemPrompt',label:'System prompt',group:'Identidad',type:'textarea',example:'## IDENTIDAD\n- Rol del agente: Agente especializado.\n- Empresa representada: Innovate.'},
  {key:'language',label:'Idioma',group:'Voz y modelos',type:'text',hint:'Código de idioma y región',example:'es-419'},
  {key:'voice',label:'ID de voz',group:'Voz y modelos',type:'number',example:'472'},
  {key:'ttsProvider',label:'Proveedor TTS',group:'Voz y modelos',type:'number',example:'2'},
  {key:'ttsModel',label:'Modelo TTS',group:'Voz y modelos',type:'text',example:'eleven_multilingual_v2'},
  {key:'voiceCustomSettings',label:'Configuración avanzada de voz',group:'Voz y modelos',type:'json',hint:'Objeto JSON',example:'{"speed":1,"stability":0.5,"similarity_boost":0.75}'},
  {key:'transcriptionModel',label:'Modelo de transcripción',group:'Voz y modelos',type:'text',example:'nova-3'},
  {key:'llmProvider',label:'Proveedor LLM',group:'Voz y modelos',type:'number',example:'1'},
  {key:'llmModel',label:'Modelo LLM',group:'Voz y modelos',type:'number',example:'12'},
  {key:'llmTemperature',label:'Temperatura',group:'Voz y modelos',type:'number',hint:'Entre 0 y 2',example:'0.3'},
  {key:'maxTokens',label:'Máximo de tokens',group:'Voz y modelos',type:'number',example:'500'},
  {key:'backchannel',label:'Confirmaciones breves',group:'Conversación',type:'boolean'},
  {key:'backchannelWords',label:'Palabras de confirmación',group:'Conversación',type:'json',hint:'Arreglo JSON',example:'["Claro","Entiendo","Sí"]'},
  {key:'idleTimeout',label:'Tiempo antes del mensaje',group:'Conversación',type:'number',example:'7'},
  {key:'idleMessages',label:'Mensajes de inactividad',group:'Conversación',type:'json',hint:'Arreglo JSON',example:'["¿Hola, sigue ahí?","Aún estoy en línea"]'},
  {key:'maxIdleMessages',label:'Máximo de mensajes',group:'Conversación',type:'number',example:'2'},
  {key:'silenceTimeout',label:'Tiempo máximo de silencio',group:'Conversación',type:'number',example:'30'},
  {key:'voicemail',label:'Buzón habilitado',group:'Buzón',type:'boolean'},
  {key:'voicemailMode',label:'Modo de buzón',group:'Buzón',type:'text',example:'hangup'},
  {key:'voicemailMessage',label:'Mensaje de buzón',group:'Buzón',type:'textarea',example:'Hola, le llamamos de Innovate. Nos comunicaremos nuevamente. Gracias.'},
  {key:'analysisPrompt',label:'Instrucciones de análisis',group:'Postproceso',type:'textarea',example:'Resume la interacción e identifica el motivo de la decisión del usuario.'},
  {key:'successEvaluationPrompt',label:'Evaluación de éxito',group:'Postproceso',type:'textarea',example:'Evalúa si se cumplieron los objetivos de la interacción.'},
  {key:'successEvaluationRubric',label:'Rúbrica',group:'Postproceso',type:'textarea',example:'Escala de 1 a 10; 1 es incumplimiento y 10 cumplimiento completo.'},
  {key:'structuredDataPrompt',label:'Extracción estructurada',group:'Postproceso',type:'textarea',example:'Extrae el nombre, la calificación y las respuestas del cuestionario.'},
  {key:'dataSchema',label:'Esquema de datos',group:'Postproceso',type:'json',hint:'Arreglo JSON',example:'[{"propName":"nombre_usuario","propType":"string","description":"Nombre confirmado"}]'},
  {key:'serverURL',label:'URL del webhook',group:'Webhook',type:'text',example:'https://backend.ejemplo.com/webhooks/sophia'},
  {key:'serverMessages',label:'Eventos enviados',group:'Webhook',type:'json',hint:'Arreglo JSON',example:'["structured-data","success-evaluation","summary"]'},
  {key:'enabled_channels',label:'Canales habilitados',group:'Webhook',type:'json',hint:'Arreglo JSON',example:'["voice"]'},
];

function display(value:unknown,type:Field['type']){if(value===undefined||value===null)return '';if(type==='json')return JSON.stringify(value,null,2);return typeof value==='string'||typeof value==='number'||typeof value==='boolean'?String(value):JSON.stringify(value)}
function parse(value:string,type:Field['type']){if(type==='boolean')return value==='true';if(type==='number')return value===''?null:Number(value);if(type==='json')return value.trim()?JSON.parse(value):[];return value}

export default function AgentEditor({id,onBack}:{id:string;onBack:()=>void}){
  const [original,setOriginal]=useState<RecordValue|null>(null);const [values,setValues]=useState<Record<string,string>>({});const [loading,setLoading]=useState(true);const [publishing,setPublishing]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [importNote,setImportNote]=useState('');const fileInput=useRef<HTMLInputElement>(null);const [openGroups,setOpenGroups]=useState<Record<string,boolean>>({Identidad:true,'Voz y modelos':true,Conversación:true,Buzón:true,Postproceso:true,Webhook:true});
  async function load(){setLoading(true);setError('');try{const response=await fetch(`/api/agents/${encodeURIComponent(id)}`,{cache:'no-store'});const payload=await response.json() as {error?:string;agent?:RecordValue};if(!response.ok||!payload.agent)throw new Error(payload.error||'No fue posible cargar el agente.');const agent=payload.agent;setOriginal(agent);setValues(Object.fromEntries(FIELDS.map(field=>[field.key,display(agent[field.key],field.type)])))}catch(err){setError(err instanceof Error?err.message:'No fue posible cargar el agente.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[id]);
  const result=useMemo(()=>{const changes:RecordValue={};const invalid:string[]=[];if(!original)return {changes,invalid};for(const field of FIELDS){try{const next=parse(values[field.key]??'',field.type);const before=original[field.key]??(field.type==='json'?[]:field.type==='boolean'?false:field.type==='number'?null:'');if(JSON.stringify(next)!==JSON.stringify(before))changes[field.key]=next}catch{invalid.push(field.label)}}return {changes,invalid}},[original,values]);
  const changedKeys=Object.keys(result.changes);
  async function importExcel(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file||!original)return;setError('');setSuccess('');setImportNote('');try{const XLSX=await import('xlsx');const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'});const sheet=workbook.Sheets['Ficha homologada'];if(!sheet)throw new Error('El archivo no contiene la hoja “Ficha homologada”.');const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:'',range:3});if(!rows.length)throw new Error('La hoja “Ficha homologada” no contiene registros.');const direct:Record<string,string>={};const promptSections=new Map<string,string[]>();let imported=0;let ignored=0;for(const row of rows){const parameter=String(row['Parámetro SophIA']??'').trim();const raw=row['Valor'];const value=raw===undefined||raw===null?'':String(raw).trim();if(!parameter||!value){ignored+=1;continue}if(parameter==='systemPrompt'||parameter.startsWith('systemPrompt ')){const section=String(row['Sección']||'Instrucciones').trim().toUpperCase();const label=String(row['Nombre homologado']||'Regla').trim();const entries=promptSections.get(section)||[];entries.push(`- ${label}: ${value}`);promptSections.set(section,entries);imported+=1;continue}if(parameter==='voiceCustomSettings.speed'){const current=original.voiceCustomSettings&&typeof original.voiceCustomSettings==='object'?original.voiceCustomSettings as RecordValue:{};direct.voiceCustomSettings=JSON.stringify({...current,speed:Number(value)},null,2);imported+=1;continue}const field=FIELDS.find(item=>item.key===parameter);if(!field){ignored+=1;continue}if(field.type==='json'){try{direct[parameter]=JSON.stringify(JSON.parse(value),null,2)}catch{throw new Error(`El valor de “${field.label}” no contiene JSON válido.`)}}else if(field.type==='boolean'){const normalized=value.toLowerCase();if(!['true','false','sí','si','no','1','0'].includes(normalized))throw new Error(`El valor de “${field.label}” debe ser Sí o No.`);direct[parameter]=['true','sí','si','1'].includes(normalized)?'true':'false'}else direct[parameter]=value;imported+=1}if(promptSections.size)direct.systemPrompt=[...promptSections].map(([section,lines])=>`## ${section}\n${lines.join('\n')}`).join('\n\n');if(!Object.keys(direct).length)throw new Error('No se encontraron valores compatibles para importar.');setValues(current=>({...current,...direct}));setImportNote(`${file.name}: ${imported} filas importadas${ignored?` · ${ignored} ignoradas`:''}. Revisa las diferencias antes de publicar.`)}catch(err){setError(err instanceof Error?err.message:'No fue posible leer el archivo Excel.')}}
  async function publish(e:FormEvent){e.preventDefault();setError('');setSuccess('');if(result.invalid.length){setError(`Corrige el formato JSON de: ${result.invalid.join(', ')}.`);return}if(!changedKeys.length)return;if(!window.confirm(`Se publicarán ${changedKeys.length} cambios en SophIA para este agente. ¿Deseas continuar?`))return;setPublishing(true);try{const response=await fetch(`/api/agents/${encodeURIComponent(id)}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({changes:result.changes})});const payload=await response.json() as {error?:string;publishedFields?:string[];agent?:RecordValue};if(!response.ok||!payload.agent)throw new Error(payload.error||'No fue posible publicar.');setSuccess(`Actualización verificada: ${payload.publishedFields?.length||0} campos publicados.`);const agent=payload.agent;setOriginal(agent);setValues(Object.fromEntries(FIELDS.map(field=>[field.key,display(agent[field.key],field.type)])))}catch(err){setError(err instanceof Error?err.message:'No fue posible publicar.')}finally{setPublishing(false)}}
  if(loading)return <section className="editor-loading"><div className="spinner"/><p>Cargando configuración completa…</p></section>;
  return <section className="agent-editor"><button className="back-button" onClick={onBack}><ArrowLeft size={15}/> Volver a agentes</button><div className="editor-heading"><div><div className="eyebrow"><span/> EDICIÓN CONTROLADA</div><h1>{typeof original?.name==='string'?original.name:'Agente'}</h1><p>{id}</p></div><div className="editor-heading-actions"><input ref={fileInput} className="hidden-file" type="file" accept=".xlsx,.xls" onChange={importExcel}/><button className="import-button" type="button" onClick={()=>fileInput.current?.click()}><Upload size={15}/> Importar Excel</button><div className="change-counter"><strong>{changedKeys.length}</strong><span>cambios</span></div></div></div>{error&&<div className="api-error"><AlertTriangle size={14}/>{error}</div>}{success&&<div className="publish-success"><Check size={15}/>{success}</div>}{importNote&&<div className="import-success"><FileSpreadsheet size={16}/>{importNote}</div>}
    <form onSubmit={publish}><div className="editor-layout"><div className="editor-fields">{Object.keys(openGroups).map(group=><section className="field-group" key={group}><button type="button" className="group-heading" onClick={()=>setOpenGroups(current=>({...current,[group]:!current[group]}))}><span>{group}</span><em>{FIELDS.filter(field=>field.group===group).length} parámetros</em><ChevronDown size={16}/></button>{openGroups[group]&&<div className="fields-grid">{FIELDS.filter(field=>field.group===group).map(field=><label className={field.type==='textarea'||field.type==='json'?'wide':''} key={field.key}><span>{field.label}<code>{field.key}</code></span>{field.type==='textarea'||field.type==='json'?<textarea rows={field.key==='systemPrompt'?12:field.type==='json'?5:3} value={values[field.key]??''} placeholder={field.example} onChange={e=>setValues(current=>({...current,[field.key]:e.target.value}))}/>:field.type==='boolean'?<select value={values[field.key]??'false'} onChange={e=>setValues(current=>({...current,[field.key]:e.target.value}))}><option value="true">Sí</option><option value="false">No</option></select>:<input type={field.type==='number'?'number':'text'} step="any" value={values[field.key]??''} placeholder={field.example} onChange={e=>setValues(current=>({...current,[field.key]:e.target.value}))}/>} {field.hint&&<small>{field.hint}{field.example?` · Ejemplo: ${field.example}`:''}</small>}</label>)}</div>}</section>)}</div>
      <aside className="changes-panel"><h2>Comparación</h2><p>Solo se enviarán los campos modificados.</p>{result.invalid.length>0&&<div className="invalid-note"><AlertTriangle size={14}/> JSON pendiente de corregir</div>}<div className="changes-list">{changedKeys.length?changedKeys.map(key=><div key={key}><strong>{FIELDS.find(field=>field.key===key)?.label||key}</strong><span>{key}</span></div>):<div className="no-changes"><Check size={18}/>Sin cambios pendientes</div>}</div><button className="publish-button" disabled={publishing||!changedKeys.length||result.invalid.length>0}><Save size={15}/>{publishing?'Publicando y verificando…':'Publicar cambios'}</button><small>Se guarda un respaldo temporal antes de escribir y luego se relee el agente.</small></aside></div></form>
  </section>
}
